name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Compile
        run: dotnet publish -c Release --output ./build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: rsync -e "ssh -o StrictHostKeyChecking=no" -avz ./build ${{ secrets.SSH_HOME }}/WitcheryResurrectedWebApi
